# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170821_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='sampledocument1/'),
        ),
    ]
