# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170904_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idocument', models.FileField(upload_to='userinputs/')),
                ('iuploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
