# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_inputdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDocument1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('sdocument', models.FileField(upload_to='sampledocument1/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
